### ISSUE TITLE
Cannot be consumed in an addon

### ISSUE THREAD

**Issue by ronco** [tim-evans/ember-page-title#31]
If you wish to wrap this addon in another addon's `dependencies` the following error occurs when building your end app:
```
Cannot read property 'registry' of undefined
TypeError: Cannot read property 'registry' of undefined
    at Class.module.exports.included (/Users/ronco/github/page-title-consumer/node_modules/page-title-wrapper/node_modules/ember-page-title/index.js
:12:13)
    at /Users/ronco/github/page-title-consumer/node_modules/ember-cli/lib/models/addon.js:244:32
    at Array.map (native)
    at Class.eachAddonInvoke (/Users/ronco/github/page-title-consumer/node_modules/ember-cli/lib/models/addon.js:242:22)
    at Class.Addon.included (/Users/ronco/github/page-title-consumer/node_modules/ember-cli/lib/models/addon.js:349:8)
    at EmberApp.<anonymous> (/Users/ronco/github/page-title-consumer/node_modules/ember-cli/lib/broccoli/ember-app.js:413:15)
    at Array.filter (native)
    at EmberApp._notifyAddonIncluded (/Users/ronco/github/page-title-consumer/node_modules/ember-cli/lib/broccoli/ember-app.js:408:45)
    at new EmberApp (/Users/ronco/github/page-title-consumer/node_modules/ember-cli/lib/broccoli/ember-app.js:106:8)
    at module.exports (/Users/ronco/github/page-title-consumer/ember-cli-build.js:6:13)
```

In this context `this` is the addon, rather than the end app, and doesn't have `this.app`.

**Comment by tim-evans** [comment]
@_@

Are there any known ways to solve this?

**Comment by ronco** [comment]
I got it to compile by switching it to this:
```
    var registry = this.app ? this.app.registry : this.registry;

    registry.add('htmlbars-ast-plugin', {
      name: 'translate-title-helper-to-page-title-helper',
      plugin: TranslateHelperName
    });
```

But the ast plugin doesn't end up translating `{{title}}` calls in the end app.  I'm guessing the plugin only runs on addon content at that point.  Might be best to skip the ast conversion in this scenario.

**Comment by tim-evans** [comment]
Unfortunately, it needs to run the AST transformation, otherwise only `page-title` will work. :/

**Comment by tim-evans** [comment]
Do you know any Embereños that may be able to help with this issue?

**Comment by ronco** [comment]
Ah yes, I see `{{title}}` is the documented way to use it (I've been using `{{page-title}}` in my testing).

**Comment by ronco** [comment]
@rwjblue do you have any suggestions on this?

I thought this would work:
```
  setupPreprocessorRegistry: function(type, registry) {
    registry.add('htmlbars-ast-plugin', {
      name: 'translate-title-helper-to-page-title-helper',
      plugin: TranslateHelperName
    });
  }
```

But no luck, the helper name in the consuming app is not translated.

**Comment by tim-evans** [comment]
Thanks for digging into this! I would love for this to work in nested addons. It's required for those experimenting with engines.

**Comment by buschtoens** [comment]
Just wanted to chip in, as I just ran into this bug while indeed experimenting with engines.

Is there a reason why we need this transpilation in the first place? Is it because of the dash?
As `{{page-title}}` is a helper and not a component it should be exempt from the required dash naming scheme and naming it `{{title}}` should work right away.

Or am I missing something?

**Comment by tim-evans** [comment]
So, we could require everyone to use `{{page-title}}`, but using `{{title}}` as a helper would collide with any property named `{{title}}` (which is quite common).

Since helpers can be called with no arguments, it becomes tricky for Ember to determine whether the call is to the parameter or the helper. The current solution decides to always choose the helper.

Going back to the transpiler, that's the only solution I've found to fix this. I would love to have some input from the ember-cli team on how to fix this, since I believe that this should be possible from nested addons.

**Comment by tim-evans** [comment]
Pinging @rwjblue! Any ideas on how to get an AST working in an addon's addon?

**Comment by tim-evans** [comment]
Solved in the most recent release.
