### ISSUE TITLE
Error installing ember-page-title on ember-cli 2.8.0

### ISSUE THREAD

**Issue by gorbypark** [tim-evans/ember-page-title#43]
root@1b981a35323d:/ember/ember-quickstart# ember install ember-page-title
Installed packages for tooling via npm.
installing ember-page-title
The `ember generate <entity-name>` command requires an entity name to be specified. For more details, use `ember help`.

ember -v output: 
ember-cli: 2.8.0
node: 6.5.0
os: linux x64

npm version 3.10.3

**Comment by ptraceur** [comment]
I'm getting this error too, but my ember version is 2.4. I guess this is not a version related bug.

ember -v output:
ember-cli: 2.4.3
node: 4.4.1
os: darwin x64

**Comment by tim-evans** [comment]
Gotcha! Will try digging into this.

**Comment by SaladFork** [comment]
I wonder if this is the harmless error that was a bug in ember-cli caused when there is no add-on blueprint (see [ember-cli#3846](https://github.com/ember-cli/ember-cli/pull/3846)). It should have been fixed by now, so I'm not sure why we're still seeing this. There was a workaround of implementing an empty `normalizeEntityName`, which might work again.

**Comment by tim-evans** [comment]
Ahh, yeah. That may be worth a try

**Comment by kyleshevlin** [comment]
I'm on 2.8.1 and getting the same error. First time using this addon, so I am unfamiliar with how it works. I'm assuming a generator is supposed to run in install? Because the addon isn't updating the title, which I assume is related to this error.

**Comment by tim-evans** [comment]
Fixed the blueprint. It seems like that ember-cli bug is back :(
